const NETHERLANDS_CITIES = [
    // Randstad - Largest urban network
  'Amsterdam',
  'Rotterdam',
  'The Hague',
  'Utrecht',
  
  // Brabantstad - Big 5 of North Brabant
  'Eindhoven',
  'Tilburg',
  'Breda',
  "'s-Hertogenbosch",
  'Helmond',
  
  // Other major cities (100,000+ population)
  'Groningen',
  'Almere',
  'Nijmegen',
  'Apeldoorn',
  'Haarlem',
  'Arnhem',
  'Enschede',
  'Zaanstad',
  'Amersfoort',
  'Haarlemmermeer',
  'Zoetermeer',
  'Leiden',
  'Dordrecht',
  
  // Medium-sized cities (50,000-100,000)
  'Emmen',
  'Zwolle',
  'Ede',
  'Delft',
  'Westland',
  'Venlo',
  'Deventer',
  'Alkmaar',
  'Leeuwarden',
  'Sittard-Geleen',
  'Hilversum',
  'Hengelo',
  'Maastricht',
  'Alphen aan den Rijn',
  'Roosendaal',
  'Purmerend',
  'Schiedam',
  'Oss',
  'Hoorn',
  'Spijkenisse',
  'Vlaardingen',
  'Almelo',
  'Gouda',
  'Velsen',
  'Den Helder',
  'Amstelveen',
  'Smallingerland',
  'Bergen op Zoom',
  'Veenendaal',
  'Katwijk',
  'Uden',
  'Zeist',
  'Barneveld',
  'Capelle aan den IJssel',
  'Súdwest-Fryslân',
  'Weststellingwerf',
  'Assen',
  'Nieuwegein',
  
  // Historic and popular cities
  'Volendam',
  'Zaanse Schans',
  'Giethoorn',
  'Kinderdijk',
  'Edam',
  'Marken',
  'Naarden',
  'Enkhuizen',
  'Kampen',
  'Middelburg',
  'Harderwijk',
  'Oudewater',
  'Schoonhoven',
  'Doesburg',
  'Gorinchem',
  'Heusden',
  'Woudrichem',
  'Elburg',
  'Zutphen',
  'Blokzijl',
  'Sloten',
  'Monnickendam'
]

module.exports = NETHERLANDS_CITIES
